=== SiChiTong/Epsilon5/Epsilon5-Java/client/src/main/resources/schemas/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://client.epsilon5.com/settings"
        xmlns:tns="http://client.epsilon5.com/settings"
        elementFormDefault="qualified">

    <element name="settings">
        <complexType>
            <all>
                <element name="window" type="tns:windowSettings"/>
                <element name="network" type="tns:networkSettings"/>
                <element name="player" type="tns:playerSettings"/>
            </all>
        </complexType>
    </element>

    <complexType name="windowSettings">
        <all>
            <element name="title" type="string"/>
            <element name="width" type="int"/>
            <element name="height" type="int"/>
            <element name="fullScreen" type="boolean"/>
            <element name="fps" type="int"/>
        </all>
    </complexType>

    <complexType name="networkSettings">
        <all>
            <element name="host" type="string"/>
            <element name="port" type="int"/>
        </all>
    </complexType>

    <complexType name="playerSettings">
        <all>
            <element name="name" type="string"/>
            <element name="password" type="string"/>
        </all>
    </complexType>

</schema>

=== SiChiTong/Epsilon5/Epsilon5-Java/client/src/main/resources/description/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://client.epsilon5.com/settings"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://client.epsilon5.com/settings ../schemas/settings.xsd">

    <player>
        <name>Marvel</name>
        <password>123</password>
    </player>

    <window>
        <title>PekaShooter</title>
        <width>320</width>
        <height>240</height>
        <fullScreen>false</fullScreen>
        <fps>100</fps>
    </window>

    <network>
        <host>193.169.33.254</host>
        <port>14567</port>
    </network>
</settings>
